# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2

jobs:
  build:
    working_directory: ~/roman
    docker:
      - image: codeaches/openjdk:12-jdk
    steps:
      - checkout
      - restore_cache:
          key: circleci-roman-kata-{{ checksum "pom.xml" }}
      - run: mvn clean test org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report install -Dmaven.test.failure.ignore=false sonar:sonar jacoco:report coveralls:report
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-roman-kata-{{ checksum "pom.xml" }}
      - store_artifacts:
          path: target/surefire-reports/TEST-roman.RomanConverterShould.xml
          destination: report.xml
      - store_test_results:
          path: target/surefire-reports
